<?php
// Code Snippets plugin — MWM ROADMAP™ · ONE-SHOT BOOTSTRAP
// DEV · Aug 11 2026 · Delete this snippet once it has run.
//
// Three chores that each need to happen exactly once:
//   1. Create the /roadmap-portal/ page carrying [mwm_roadmap_portal].
//   2. Mail the generated access code to Michael.
//   3. Delete the code from wp_options so it does not live there forever.
//
// 🔴 The access code goes WordPress → Michael's inbox and is never returned to
// an agent, a log, or a chat transcript. That is the whole reason this runs
// server-side instead of being read out of options.php.

if ( ! defined( 'ABSPATH' ) ) { exit; }

define( 'MWM_RM_BOOTSTRAP_VERSION', '1' );

function mwm_rm_bootstrap() {

	$slug = 'roadmap-portal';
	$page = get_page_by_path( $slug );

	if ( ! $page ) {
		$id = wp_insert_post( array(
			'post_title'     => 'Your ROADMAP',
			'post_name'      => $slug,
			'post_content'   => '[mwm_roadmap_portal]',
			'post_status'    => 'publish',
			'post_type'      => 'page',
			'comment_status' => 'closed',
			'ping_status'    => 'closed',
		) );
		if ( is_wp_error( $id ) || ! $id ) {
			error_log( '[MWM ROADMAP bootstrap] could not create the portal page' );
			return;
		}
		update_post_meta( $id, '_wp_page_template', 'default' );
		// Keep it out of search and out of the nav — clients arrive by link.
		update_option( 'mwm_roadmap_portal_page_id', (int) $id, false );
	} else {
		update_option( 'mwm_roadmap_portal_page_id', (int) $page->ID, false );
	}

	$code = get_option( 'mwm_roadmap_seed_code_once' );
	if ( $code ) {
		$url  = home_url( '/' . $slug . '/' );
		$body = "The ROADMAP portal is live.\n\n"
		      . "Address:      " . $url . "\n"
		      . "Client:       Zerlotini Brothers Construction\n"
		      . "Email:        thiago@zbrothersconstruction.com\n"
		      . "Access code:  " . $code . "\n\n"
		      . "Both are needed to sign in. Access codes cannot be recovered — if it is\n"
		      . "lost we issue a new one.\n\n"
		      . "This code was generated by WordPress and sent straight to you. It was not\n"
		      . "read by any agent and is not in any chat transcript. It has now been deleted\n"
		      . "from the database, so this email is the only copy.\n";

		wp_mail( 'michael@mwmcreations.com', 'ROADMAP portal — Z Brothers access code', $body );
	}

	delete_option( 'mwm_roadmap_seed_code_once' );
	update_option( 'mwm_roadmap_bootstrap', MWM_RM_BOOTSTRAP_VERSION, false );
}

add_action( 'init', function () {
	if ( get_option( 'mwm_roadmap_bootstrap' ) !== MWM_RM_BOOTSTRAP_VERSION ) {
		mwm_rm_bootstrap();
	}
}, 20 );
